"""empty message

Revision ID: ef439db67684
Revises: a129ef20747e
Create Date: 2020-05-21 23:43:49.136371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef439db67684'
down_revision = 'a129ef20747e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'confirmed')
    # ### end Alembic commands ###
